# -*- coding: utf-8 -*-
"""finetune_and_evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ts29OPeHtC_ES-4GMsgDxgiNe1Xn9sX6

# Vedaz Astrologer — Qwen2.5 LoRA Fine-Tune (Colab)

**Runtime:** `Runtime -> Change runtime type -> T4 GPU` (free tier works) or `A100` (Colab Pro, faster).

This notebook:
1. Loads the raw chat dataset (upload it when prompted, or point to a path).
2. Robustly parses it (the source file has inconsistent record separators).
3. Generates **base-model** answers to 5 fixed test prompts *before* training (for the before/after comparison).
4. LoRA fine-tunes Qwen2.5-7B-Instruct in 4-bit.
5. Logs training loss and plots a loss curve.
6. Generates **fine-tuned** answers to the same 5 prompts.
7. Saves a side-by-side `sample_outputs_before_after.md`.
8. Saves the LoRA adapter only (small, git-friendly) as a zip you can download and push to GitHub.

Run all cells top to bottom (`Runtime -> Run all`).
"""

!pip install -q trl==0.19.1 transformers accelerate peft bitsandbytes datasets matplotlib

!pip install -q --force-reinstall trl==0.19.1

import torch
print("GPU available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Device:", torch.cuda.get_device_name(0))
    print("VRAM (GB):", round(torch.cuda.get_device_properties(0).total_memory / 1e9, 1))
else:
    raise RuntimeError("No GPU detected — go to Runtime > Change runtime type > GPU before continuing.")

"""## 1. Upload the dataset

Upload `Chat_Data_for_assessment_of_applicants.json` (the raw file — messy formatting is fine, the parser below handles it).
"""

from google.colab import files
uploaded = files.upload()
RAW_DATA_PATH = list(uploaded.keys())[0]
print("Using:", RAW_DATA_PATH)

"""## 2. Robustly parse the dataset"""

import json, re
from pathlib import Path

def parse_messy_chat_file(path):
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    starts = [m.start() for m in re.finditer(r'\{\s*"messages"', text)]
    decoder = json.JSONDecoder(strict=False)
    records = []
    for s in starts:
        obj, _ = decoder.raw_decode(text, s)
        records.append(obj)
    return records

def clean_and_dedupe(records):
    seen, cleaned = set(), []
    for r in records:
        msgs = r.get("messages", [])
        if not msgs or msgs[0]["role"] != "system":
            continue
        key = json.dumps(msgs, ensure_ascii=False)
        if key in seen:
            continue
        seen.add(key)
        cleaned.append({"messages": msgs})
    return cleaned

records = clean_and_dedupe(parse_messy_chat_file(RAW_DATA_PATH))
print(f"Recovered {len(records)} clean training conversations")

CLEAN_JSONL_PATH = "vedaz_astrologer_sft.jsonl"
with open(CLEAN_JSONL_PATH, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

"""## 3. Config"""

BASE_MODEL = "Qwen/Qwen2.5-7B-Instruct"   # swap for a Qwen3 checkpoint if/when you have access
OUTPUT_DIR = "qwen-vedaz-astrologer-lora"
MAX_SEQ_LEN = 2048
NUM_EPOCHS = 3

# Fixed evaluation prompts used for the before/after comparison.
EVAL_PROMPTS = [
    "Mera breakup ho gaya hai, bahut akela feel ho raha hai. Career kaisa rahega mera is saal?",
    "DOB 12 July 1998, 6:30 AM, Delhi. Kab tak achi job milegi mujhe?",
    "मेरी शादी में बहुत देरी हो रही है, परिवार वाले परेशान कर रहे हैं। DOB 3 Feb 1995, रात 10 बजे, भोपाल।",
    "Should I invest my savings based on what my kundli says about wealth this year?",
    "Meri health ko lekar kundli mein kuch bura toh nahi dikh raha? Bahut dar lag raha hai.",
]

"""## 4. Load base model + tokenizer (4-bit)"""

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=quant_config,
    device_map="auto",
    torch_dtype=torch.bfloat16,
)

"""## 5. Generate BASE model answers (before fine-tuning)"""

def generate_reply(model, tokenizer, user_prompt, max_new_tokens=350):
    messages = [
        {"role": "system", "content": "You are Vedaz's AI Vedic astrologer. You give compassionate, balanced, non-fatalistic guidance."},
        {"role": "user", "content": user_prompt},
    ]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            pad_token_id=tokenizer.eos_token_id,
        )
    reply = tokenizer.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
    return reply.strip()

base_outputs = []
for p in EVAL_PROMPTS:
    print("Prompt:", p[:60], "...")
    reply = generate_reply(model, tokenizer, p)
    base_outputs.append(reply)
    print(reply[:200], "\n---")

with open("base_outputs.json", "w", encoding="utf-8") as f:
    json.dump(dict(zip(EVAL_PROMPTS, base_outputs)), f, ensure_ascii=False, indent=2)

"""## 6. Attach LoRA + prepare training data"""

from peft import LoraConfig, get_peft_model, PeftModel
from datasets import Dataset

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

rows = []
with open(CLEAN_JSONL_PATH, encoding="utf-8") as f:
    for line in f:
        rec = json.loads(line)
        text = tokenizer.apply_chat_template(rec["messages"], tokenize=False, add_generation_prompt=False)
        rows.append({"text": text})
train_dataset = Dataset.from_list(rows)
print(f"Training on {len(train_dataset)} examples")

"""## 7. Train (with loss logging)"""

import trl, inspect
from trl import SFTTrainer, SFTConfig

# Figure out the correct kwarg name for this installed version of TRL
_sft_params = inspect.signature(SFTConfig.__init__).parameters
_seq_len_kwarg = "max_seq_length" if "max_seq_length" in _sft_params else "max_length"
print(f"TRL {trl.__version__} — using '{_seq_len_kwarg}'")

sft_config = SFTConfig(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=8,
    num_train_epochs=NUM_EPOCHS,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.03,
    logging_steps=1,
    save_strategy="epoch",
    bf16=True,
    **{_seq_len_kwarg: MAX_SEQ_LEN},
    dataset_text_field="text",
    packing=False,
    report_to="none",
)

# tokenizer= vs processing_class= also changed in newer TRL
_trainer_params = inspect.signature(SFTTrainer.__init__).parameters
_tok_kwarg = "tokenizer" if "tokenizer" in _trainer_params else "processing_class"

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=train_dataset,
    **{_tok_kwarg: tokenizer},
)

train_result = trainer.train()

"""## 8. Save training logs + loss curve"""

import pandas as pd
import matplotlib.pyplot as plt

log_history = trainer.state.log_history
loss_rows = [r for r in log_history if "loss" in r]
df = pd.DataFrame(loss_rows)
df.to_csv("training_logs.csv", index=False)

with open("training_logs.txt", "w") as f:
    for r in loss_rows:
        f.write(f"step={r.get('step')}\tepoch={round(r.get('epoch', 0), 3)}\tloss={r.get('loss')}\n")

plt.figure(figsize=(8, 5))
plt.plot(df["step"], df["loss"], marker="o", markersize=3)
plt.xlabel("Training step")
plt.ylabel("Loss")
plt.title("Vedaz Astrologer LoRA fine-tune — training loss")
plt.grid(alpha=0.3)
plt.savefig("loss_curve.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved training_logs.csv, training_logs.txt, loss_curve.png")

"""## 9. Generate FINE-TUNED model answers (same prompts, after training)"""

model.eval()
finetuned_outputs = []
for p in EVAL_PROMPTS:
    print("Prompt:", p[:60], "...")
    reply = generate_reply(model, tokenizer, p)
    finetuned_outputs.append(reply)
    print(reply[:200], "\n---")

with open("finetuned_outputs.json", "w", encoding="utf-8") as f:
    json.dump(dict(zip(EVAL_PROMPTS, finetuned_outputs)), f, ensure_ascii=False, indent=2)

"""## 10. Build the side-by-side before/after markdown file"""

with open("base_outputs.json", encoding="utf-8") as f:
    base_map = json.load(f)
with open("finetuned_outputs.json", encoding="utf-8") as f:
    ft_map = json.load(f)

lines = ["# Before vs. After Fine-Tuning — Sample Outputs\n",
         f"Base model: `{BASE_MODEL}`  |  LoRA rank: 16  |  Epochs: {NUM_EPOCHS}\n"]

for i, prompt in enumerate(EVAL_PROMPTS, 1):
    lines.append(f"## Prompt {i}\n> {prompt}\n")
    lines.append(f"**Base model (before fine-tuning):**\n\n{base_map[prompt]}\n")
    lines.append(f"**Fine-tuned model (after):**\n\n{ft_map[prompt]}\n")
    lines.append("---\n")

with open("sample_outputs_before_after.md", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Saved sample_outputs_before_after.md")

"""## 11. Save the LoRA adapter only (small, git-friendly)

This saves **just the adapter weights** (a few tens of MB for r=16 on a 7B model) — not the merged full model.

"""

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

import subprocess
subprocess.run(["du", "-sh", OUTPUT_DIR])

import shutil
shutil.make_archive("qwen-vedaz-astrologer-lora", "zip", OUTPUT_DIR)
print("Zipped adapter -> qwen-vedaz-astrologer-lora.zip")

"""## 12. Download everything


"""

from google.colab import files as colab_files
for fname in ["qwen-vedaz-astrologer-lora.zip", "training_logs.csv", "training_logs.txt",
              "loss_curve.png", "sample_outputs_before_after.md",
              "base_outputs.json", "finetuned_outputs.json"]:
    colab_files.download(fname)